name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Update apt cache
      run: sudo apt-get update
    - name: Install dependencies
      run: sudo apt-get install -y g++ make libglfw3-dev libglew-dev libglm-dev libfreetype6-dev libsqlite3-dev
    - name: Build all (debug)
      run: make all config=debug
    - name: Build all (release)
      run: make all config=release
    - name: Run tests
      run: |
        cd tests
        make
        ./build/test_suite
